#pragma once
// emit-agents-md: sync an icmg-managed routing block into AGENTS.md so every
// non-Claude coding agent (Cursor, Copilot, Codex, Aider, Gemini CLI, ...) that
// reads the AGENTS.md standard inherits icmg-first behavior.
//
// Pure + header-only so the merge semantics are unit-testable without touching
// the filesystem — same pattern as wakeup_format.hpp / recall_index.hpp.
//
// Design: the block lives between HTML-comment markers. sync() REPLACES the
// content between markers if present (idempotent), else APPENDS the block while
// preserving any hand-written content above it. icmg never clobbers user prose.

#include <string>

namespace icmg::cli {

inline const char* kAgentsMdStart = "<!-- icmg:start -->";
inline const char* kAgentsMdEnd   = "<!-- icmg:end -->";

// Wrap a routing-block body between the managed markers.
inline std::string wrapIcmgBlock(const std::string& body) {
    return std::string(kAgentsMdStart) + "\n" + body + "\n" + std::string(kAgentsMdEnd);
}

// Insert or replace the icmg-managed block in existing AGENTS.md content.
//  - markers present  -> replace the span between them (idempotent re-emit)
//  - markers absent    -> append the block, keeping existing user content above
inline std::string syncAgentsMd(const std::string& existing, const std::string& body) {
    const std::string block = wrapIcmgBlock(body);
    const std::string startTok = kAgentsMdStart;
    const std::string endTok   = kAgentsMdEnd;

    auto s = existing.find(startTok);
    auto e = existing.find(endTok);
    if (s != std::string::npos && e != std::string::npos && e >= s) {
        std::string before = existing.substr(0, s);
        std::string after  = existing.substr(e + endTok.size());
        return before + block + after;
    }
    // Append: preserve user content, ensure a blank line separates it.
    std::string result = existing;
    if (!result.empty() && result.back() != '\n') result += "\n";
    if (!result.empty()) result += "\n";
    result += block + "\n";
    return result;
}

// Default routing-block body: the icmg-first decision tree, tool-agnostic.
inline std::string icmgRoutingBlock() {
    return
        "## icmg routing (auto-generated by `icmg emit-agents-md`)\n\n"
        "This project uses **icmg** for token-efficient code navigation + memory.\n"
        "Before a native tool call, prefer the icmg equivalent:\n\n"
        "| Want to | Use |\n"
        "|---|---|\n"
        "| Read a large file | `icmg context <file>` |\n"
        "| Find a symbol | `icmg graph symbol <Name>` |\n"
        "| Locate a file by name | `icmg find --name <partial>` |\n"
        "| Find where X lives across files | `icmg find \"<intent>\"` |\n"
        "| Search code | `icmg run grep ...` |\n"
        "| Recall a past decision | `icmg recall \"<query>\"` |\n"
        "| Start a task | `icmg pack \"<task>\"` |\n"
        "| Run a noisy command | `icmg run <cmd>` |\n"
        "| 2+ independent steps | `icmg parallel --task .. --task ..` |\n";
}

} // namespace icmg::cli
