// v1.13.0: `icmg hook init <name>` — scaffold custom hook script.

#include "../base_command.hpp"
#include "../../core/registry.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace icmg::cli {

class HookInitCommand : public BaseCommand {
public:
    std::string name()        const override { return "hook-init"; }
    std::string description() const override {
        return "Scaffold custom hook script in .claude/hooks/";
    }

    void usage() const override {
        std::cout <<
            "Usage: icmg hook-init <name> [--event EVENT] [--tool TOOL]\n\n"
            "Events: PreToolUse PostToolUse UserPromptSubmit Stop SessionStart\n"
            "Generates .claude/hooks/icmg-custom-<name>.sh + registers in\n"
            ".claude/settings.local.json. Template uses `icmg hookio` for stdin parse.\n";
    }

    int run(const std::vector<std::string>& args) override {
        if (args.empty() || hasFlag(args, "--help")) { usage(); return 0; }
        std::string hook_name = args[0];
        std::string event = flagValue(args, "--event", "PostToolUse");
        std::string tool  = flagValue(args, "--tool",  "");

        fs::path dir = ".claude/hooks";
        std::error_code ec;
        fs::create_directories(dir, ec);
        if (ec) {
            std::cerr << "hook-init: mkdir failed: " << ec.message() << "\n";
            return 1;
        }
        fs::path script = dir / ("icmg-custom-" + hook_name + ".sh");
        if (fs::exists(script, ec)) {
            std::cerr << "hook-init: " << script.string()
                      << " already exists (no overwrite)\n";
            return 1;
        }
        {
            std::ofstream f(script);
            if (!f) { std::cerr << "hook-init: write failed\n"; return 1; }
            f << "#!/usr/bin/env bash\n"
              << "# Custom hook: " << hook_name << "\n"
              << "# Event: " << event;
            if (!tool.empty()) f << " (tool: " << tool << ")";
            f << "\n"
              << "# Generated by `icmg hook-init`. Edit freely.\n"
              << "set -uo pipefail\n"
              << "command -v icmg >/dev/null 2>&1 || exit 0\n"
              << "\n"
              << "INPUT=$(cat)\n";
            if (event == "PreToolUse" || event == "PostToolUse") {
                f << "TOOL=$(printf '%s' \"$INPUT\" | icmg hookio get tool_name 2>/dev/null)\n"
                  << "FILE=$(printf '%s' \"$INPUT\" | icmg hookio get tool_input.file_path 2>/dev/null)\n";
            } else if (event == "UserPromptSubmit") {
                f << "PROMPT=$(printf '%s' \"$INPUT\" | icmg hookio get prompt 2>/dev/null)\n";
            }
            f << "\n"
              << "# TODO: your logic here. Emit injection via:\n"
              << "#   icmg hookio emit " << event << " --ctx \"your msg\"\n"
              << "exit 0\n";
        }
        std::cout << "hook-init: wrote " << script.string() << "\n";
        std::cout << "Register in .claude/settings.local.json `hooks." << event
                  << "` array. Example:\n"
                  << "  {\"matcher\":\"" << (tool.empty() ? "*" : tool) << "\","
                  << "\"hooks\":[{\"type\":\"command\",\"command\":\"bash "
                  << script.string() << "\"}]}\n";
        return 0;
    }
};

ICMG_REGISTER_COMMAND("hook-init", HookInitCommand);

}  // namespace icmg::cli
